In [77]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

## Reading the dataset

In [78]:
df = pd.read_csv(r'C:\Users\Arijit\Downloads\archive\Airbnb_Open_Data.csv', low_memory=False)
df

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

## Exploring the dataset

In [79]:
print("Total rows : ", df.shape[0])
print("\nTotal columns : ", df.shape[1])
print("\nData dimension : ", df.ndim)
print("\nData info : ", df.info())

Total rows :  102599

Total columns :  26

Data dimension :  2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

Data info :  None

In [80]:
df.describe()

,id,host id,lat,long,Construction year,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
count,1.025990e+05,1.025990e+05,102591.000000,102591.000000,102385.000000,102190.000000,102416.000000,86720.000000,102273.000000,102280.000000,102151.000000
mean,2.914623e+07,4.925411e+10,40.728094,-73.949644,2012.487464,8.135845,27.483743,1.374022,3.279106,7.936605,141.133254
std,1.625751e+07,2.853900e+10,0.055857,0.049521,5.765556,30.553781,49.508954,1.746621,1.284657,32.218780,135.435024
min,1.001254e+06,1.236005e+08,40.499790,-74.249840,2003.000000,-1223.000000,0.000000,0.010000,1.000000,1.000000,-10.000000
25%,1.508581e+07,2.458333e+10,40.688740,-73.982580,2007.000000,2.000000,1.000000,0.220000,2.000000,1.000000,3.000000
50%,2.913660e+07,4.911774e+10,40.722290,-73.954440,2012.000000,3.000000,7.000000,0.740000,3.000000,1.000000,96.000000
75%,4.320120e+07,7.399650e+10,40.762760,-73.932350,2017.000000,5.000000,30.000000,2.000000,4.000000,2.000000,269.000000
max,5.736742e+07,9.876313e+10,40.916970,-73.705220,2022.000000,5645.000000,1024.000000,90.000000,5.000000,332.000000,3677.000000

## Fixing column names

In [81]:
# See how many columns are there
print(df.columns)

# Drop columns which are not important
columns_to_drop = [
    'last review', 'reviews per month',
    'review rate number', 'calculated host listings count',
    'availability 365', 'house_rules', 'license',
    'country code'
]

# Columns droped
df.drop(columns=columns_to_drop, inplace=True)
print(df.columns)

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')
Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews'],
      dtype='object')

In [82]:
# Fixing column names
print(df.columns)

print()

# Check for errors
print("Total number containing columns : ", df.columns[df.columns == df.columns.str.contains(r'[0-9]')])
print("\nTotal special character containing columns : ", df.columns[df.columns == df.columns.str.contains(r'[^A-Za-z0-9\s]')])
print("\nTotal upper case letter containing columns : ", df.columns[df.columns != df.columns.str.lower()])
print("\nTotal space containing columns : ", df.columns[df.columns != df.columns.str.strip()])
print("\nTotal inner space containing columns : ", df.columns[df.columns.str.contains(' ')])

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews'],
      dtype='object')

Total number containing columns :  Index([], dtype='object')

Total special character containing columns :  Index([], dtype='object')

Total upper case letter containing columns :  Index(['NAME', 'Construction year'], dtype='object')

Total space containing columns :  Index([], dtype='object')

Total inner space containing columns :  Index(['host id', 'host name', 'neighbourhood group', 'room type',
       'Construction year', 'service fee', 'minimum nights',
       'number of reviews'],
      dtype='object')

In [83]:
# We have to fix two things in column names
# upper case, inner spaces

df.columns = (
    df.columns.str.lower()
    .str.replace(" ", "_")
)

df.columns

Index(['id', 'name', 'host_id', 'host_identity_verified', 'host_name',
       'neighbourhood_group', 'neighbourhood', 'lat', 'long', 'country',
       'instant_bookable', 'cancellation_policy', 'room_type',
       'construction_year', 'price', 'service_fee', 'minimum_nights',
       'number_of_reviews'],
      dtype='object')

## Fixing individual columns

In [84]:
df

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,False,strict,Private room,2020.0,$966,$193,10.0,9.0
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,True,flexible,Private room,2005.0,$620,$124,3.0,0.0
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,False,flexible,Private room,2003.0,$844,$169,1.0,0.0
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,True,moderate,Private room,2016.0,$837,$167,1.0,1.0
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,True,moderate,Private room,2009.0,$988,$198,3.0,0.0
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0

In [85]:
# cleaning object type columns
for column in df.columns:
    if df[column].dtypes == "object":
        print(column)

name
host_identity_verified
host_name
neighbourhood_group
neighbourhood
country
instant_bookable
cancellation_policy
room_type
price
service_fee

In [ ]:
df['name'] = (df['name']
            .str.strip()
            .str.replace(r'[^A-Za-z\s]', '', regex=True)
            .str.replace(" ", "_")
            .str.lower()
)
df.loc[df['name']=="_"]

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews
19070,11533697,_,45358141126,verified,Hector,Brooklyn,Downtown Brooklyn,40.69569,-73.98249,United States,False,moderate,Private room,2004.0,$499,$100,1.0,0.0
28296,16629217,_,4752601131,unconfirmed,Angela,Queens,Flushing,40.76483,-73.79583,United States,True,moderate,Entire home/apt,2006.0,"$1,159",$232,1.0,49.0
55964,31910253,_,91849562472,verified,Xin,Queens,Flushing,40.73984,-73.81390,United States,True,strict,Private room,2016.0,$274,$55,30.0,8.0
57731,32886167,_,36030675805,verified,Xin,Queens,Flushing,40.74262,-73.81538,United States,True,flexible,Private room,2010.0,$170,$34,30.0,9.0
66186,37555864,_,75554433402,unconfirmed,Harry,Brooklyn,Gravesend,40.58793,-73.98866,United States,False,moderate,Entire home/apt,2015.0,$173,$35,30.0,6.0
67513,38288766,_,19246848294,unconfirmed,Zena,Queens,Flushing,40.75203,-73.83003,United States,False,flexible,Entire home/apt,2010.0,$469,$94,30.0,46.0
76234,43105374,_,38767647025,unconfirmed,Hector,Brooklyn,Downtown Brooklyn,40.69569,-73.98249,United States,False,moderate,Private room,2004.0,$499,$100,1.0,0.0
88892,50096388,_,94540702595,unconfirmed,Hector,Brooklyn,Downtown Brooklyn,40.69569,-73.98249,United States,True,strict,Private room,2004.0,$499,$100,1.0,0.0

In [ ]:
# Deleting specific rows by condition
df = df.drop(df[df['name'] == '_'].index)

In [98]:
len(df['name'])-df['name'].nunique()

43456

In [99]:
df['name'].duplicated().sum()

np.int64(43455)

In [106]:
print(df['host_identity_verified'].value_counts())
print(df['host_identity_verified'].unique())

df['host_identity_verified'] = df['host_identity_verified'].replace(
    {
        "unconfirmed":"unverified"
    }
)
print(df['host_identity_verified'].unique())

host_identity_verified
unconfirmed    51195
verified       51107
Name: count, dtype: int64
['unconfirmed' 'verified' nan]
['unverified' 'verified' nan]

In [ ]:
df['host_name'] = (df['host_name']
                .str.strip()
                .str.replace(r'[^A-Za-z\s]', '', regex=True)
                .str.lower()
)
df['host_name']

0            madaline
1               jenna
2               elise
3               garry
4              lyndon
             ...
102594           krik
102595          mifan
102596          megan
102597    christopher
102598        rebecca
Name: host_name, Length: 102591, dtype: object

In [119]:
print(df['neighbourhood_group'].unique())
print(df['neighbourhood_group'].value_counts())

df['neighbourhood_group'] = df['neighbourhood_group'].replace(
    {
        "manhatan":"Manhattan",
        "brookln":"Brooklyn"
    }
)
print(df['neighbourhood_group'].unique())
print(df['neighbourhood_group'].value_counts())

['Brooklyn' 'Manhattan' 'brookln' 'manhatan' 'Queens' nan 'Staten Island'
 'Bronx']
neighbourhood_group
Manhattan        43792
Brooklyn         41838
Queens           13263
Bronx             2712
Staten Island      955
brookln              1
manhatan             1
Name: count, dtype: int64
['Brooklyn' 'Manhattan' 'Queens' nan 'Staten Island' 'Bronx']
neighbourhood_group
Manhattan        43793
Brooklyn         41839
Queens           13263
Bronx             2712
Staten Island      955
Name: count, dtype: int64

In [122]:
print(df['neighbourhood'].value_counts())
print(df['neighbourhood'].unique())

df['neighbourhood'] = (df['neighbourhood']
                       .str.strip()
                       .str.replace(r'[^A-Za-z\s]', '', regex=True)
                       .str.lower()
)

neighbourhood
Bedford-Stuyvesant        7937
Williamsburg              7775
Harlem                    5466
Bushwick                  4982
Hell's Kitchen            3965
                          ...
Rossville                    3
Gerritsen Beach              3
Fort Wadsworth               2
Glen Oaks                    2
Chelsea, Staten Island       1
Name: count, Length: 224, dtype: int64
['Kensington' 'Midtown' 'Harlem' 'Clinton Hill' 'East Harlem'
 'Murray Hill' 'Bedford-Stuyvesant' "Hell's Kitchen" 'Upper West Side'
 'Chinatown' 'South Slope' 'West Village' 'Williamsburg' 'Fort Greene'
 'Chelsea' 'Crown Heights' 'Park Slope' 'Windsor Terrace' 'Inwood'
 'East Village' 'Greenpoint' 'Bushwick' 'Flatbush' 'Lower East Side'
 'Prospect-Lefferts Gardens' 'Long Island City' 'Kips Bay' 'SoHo'
 'Upper East Side' 'Prospect Heights' 'Washington Heights' 'Woodside'
 'Brooklyn Heights' 'Carroll Gardens' 'Gowanus' 'Flatlands' 'Cobble Hill'
 'Flushing' 'Boerum Hill' 'Sunnyside' 'DUMBO' 'St. George' 'Highbridge'
 'Financial District' 'Ridgewood' 'Morningside Heights' 'Jamaica'
 'Middle Village' 'NoHo' 'Ditmars Steinway' 'Flatiron District'
 'Roosevelt Island' 'Greenwich Village' 'Little Italy' 'East Flatbush'
 'Tompkinsville' 'Astoria' 'Clason Point' 'Eastchester' 'Kingsbridge'
 'Two Bridges' 'Queens Village' 'Rockaway Beach' 'Forest Hills' 'Nolita'
 'Woodlawn' 'University Heights' 'Gravesend' 'Gramercy' 'Allerton' nan
 'East New York' 'Theater District' 'Concourse Village' 'Sheepshead Bay'
 'Emerson Hill' 'Fort Hamilton' 'Bensonhurst' 'Tribeca' 'Shore Acres'
 'Sunset Park' 'Concourse' 'Elmhurst' 'Brighton Beach' 'Jackson Heights'
 'Cypress Hills' 'St. Albans' 'Arrochar' 'Rego Park' 'Wakefield' 'Clifton'
 'Bay Ridge' 'Graniteville' 'Spuyten Duyvil' 'Stapleton' 'Briarwood'
 'Ozone Park' 'Columbia St' 'Vinegar Hill' 'Mott Haven' 'Longwood'
 'Canarsie' 'Battery Park City' 'Civic Center' 'East Elmhurst'
 'New Springville' 'Morris Heights' 'Arverne' 'Cambria Heights'
 'Tottenville' 'Mariners Harbor' 'Concord' 'Borough Park' 'Bayside'
 'Downtown Brooklyn' 'Port Morris' 'Fieldston' 'Kew Gardens' 'Midwood'
 'College Point' 'Mount Eden' 'City Island' 'Glendale' 'Port Richmond'
 'Red Hook' 'Richmond Hill' 'Bellerose' 'Maspeth' 'Williamsbridge'
 'Soundview' 'Woodhaven' 'Woodrow' 'Co-op City' 'Stuyvesant Town'
 'Parkchester' 'North Riverdale' 'Dyker Heights' 'Bronxdale' 'Sea Gate'
 'Riverdale' 'Kew Gardens Hills' 'Bay Terrace' 'Norwood'
 'Claremont Village' 'Whitestone' 'Fordham' 'Bayswater' 'Navy Yard'
 'Brownsville' 'Eltingville' 'Fresh Meadows' 'Mount Hope'
 'Lighthouse Hill' 'Springfield Gardens' 'Howard Beach' 'Belle Harbor'
 'Jamaica Estates' 'Van Nest' 'Morris Park' 'West Brighton' 'Far Rockaway'
 'South Ozone Park' 'Tremont' 'Corona' 'Great Kills' 'Manhattan Beach'
 'Marble Hill' 'Dongan Hills' 'Castleton Corners' 'East Morrisania'
 'Hunts Point' 'Neponsit' 'Pelham Bay' 'Randall Manor' 'Throgs Neck'
 'Todt Hill' 'West Farms' 'Silver Lake' 'Morrisania' 'Laurelton'
 'Grymes Hill' 'Holliswood' 'Pelham Gardens' 'Belmont' 'Rosedale'
 'Edgemere' 'New Brighton' 'Midland Beach' 'Baychester' 'Melrose'
 'Bergen Beach' 'Richmondtown' 'Howland Hook' 'Schuylerville'
 'Coney Island' 'New Dorp Beach' "Prince's Bay" 'South Beach' 'Bath Beach'
 'Jamaica Hills' 'Oakwood' 'Castle Hill' 'Hollis' 'Douglaston' 'Huguenot'
 'Olinville' 'Edenwald' 'Grant City' 'Westerleigh'
 'Bay Terrace, Staten Island' 'Westchester Square' 'Little Neck'
 'Fort Wadsworth' 'Rosebank' 'Unionport' 'Mill Basin' 'Arden Heights'
 "Bull's Head" 'New Dorp' 'Rossville' 'Breezy Point' 'Willowbrook'
 'Glen Oaks' 'Gerritsen Beach' 'Chelsea, Staten Island']

In [140]:
print(df['country'].value_counts())
print(df['country'].unique())
print(df['country'].nunique())

country
United States    102059
Name: count, dtype: int64
['United States' nan]
1

In [142]:
df['instant_bookable'].value_counts()

instant_bookable
False    51470
True     51016
Name: count, dtype: int64

In [144]:
print(df['cancellation_policy'].value_counts())

cancellation_policy
moderate    34339
strict      34104
flexible    34072
Name: count, dtype: int64

In [146]:
print(df['room_type'].value_counts())

df['room_type'] = df['room_type'].astype(str).str.replace('/', ' ')
df['room_type'].value_counts()

room_type
Entire home/apt    53698
Private room       46551
Shared room         2226
Hotel room           116
Name: count, dtype: int64

room_type
Entire home apt    53698
Private room       46551
Shared room         2226
Hotel room           116
Name: count, dtype: int64

In [153]:
print(df['price'].dtype)

df['price'] = (df['price']
               .str.strip()
               .str.replace(" ", "")
               .str.replace(r'[^0-9]', '', regex=True)
)
df['price'] = df['price'].replace(np.nan, df['price'].mode()[0])
df['price'] = df['price'].astype(str).astype(int)
df['price'].dtype

object

dtype('int64')

In [157]:
print(df['service_fee'].dtype)

df['service_fee'] = (df['service_fee']
                    .str.strip()
                    .str.replace(r'[^0-9]', '', regex=True)
                    .replace(np.nan, df['service_fee'].mode()[0])
                    .astype(str).astype(int)
)
print(df['service_fee'].dtype)

object
int64

In [158]:
df

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews
0,1001254,clean__quiet_apt_home_by_the_park,80014485718,unverified,madaline,Brooklyn,kensington,40.64749,-73.97237,United States,False,strict,Private room,2020.0,966,193,10.0,9.0
1,1002102,skylit_midtown_castle,52335172823,verified,jenna,Manhattan,midtown,40.75362,-73.98377,United States,False,moderate,Entire home apt,2007.0,142,28,30.0,45.0
2,1002403,the_village_of_harlemnew_york_,78829239556,NaN,elise,Manhattan,harlem,40.80902,-73.94190,United States,True,flexible,Private room,2005.0,620,124,3.0,0.0
3,1002755,NaN,85098326012,unverified,garry,Brooklyn,clinton hill,40.68514,-73.95976,United States,True,moderate,Entire home apt,2005.0,368,74,30.0,270.0
4,1003689,entire_apt_spacious_studioloft_by_central_park,92037596077,verified,lyndon,Manhattan,east harlem,40.79851,-73.94399,United States,False,moderate,Entire home apt,2009.0,204,41,10.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,spare_room_in_williamsburg,12312296767,verified,krik,Brooklyn,williamsburg,40.70862,-73.94651,United States,False,flexible,Private room,2003.0,844,169,1.0,0.0
102595,6092990,best_location_near_columbia_u,77864383453,unverified,mifan,Manhattan,morningside heights,40.80460,-73.96545,United States,True,moderate,Private room,2016.0,837,167,1.0,1.0
102596,6093542,comfy_bright_room_in_brooklyn,69050334417,unverified,megan,Brooklyn,park slope,40.67505,-73.98045,United States,True,moderate,Private room,2009.0,988,198,3.0,0.0
102597,6094094,big_studioone_stop_from_midtown,11160591270,unverified,christopher,Queens,long island city,40.74989,-73.93777,United States,True,strict,Entire home apt,2015.0,546,109,2.0,5.0
102598,6094647,_sf_luxury_studio,68170633372,unverified,rebecca,Manhattan,upper west side,40.76807,-73.98342,United States,False,flexible,Entire home apt,2010.0,1032,206,1.0,0.0

In [162]:
# Now integer type columns
for column in df.columns:
    if df[column].dtypes == "int64" or df[column].dtypes == "float64":
        if column == "price" or column == "service_fee":
            continue 
        print(column)

id
host_id
lat
long
construction_year
minimum_nights
number_of_reviews

In [164]:
df[['id', 'host_id', 'lat', 'long', 'construction_year', 'minimum_nights', 'number_of_reviews']]

,id,host_id,lat,long,construction_year,minimum_nights,number_of_reviews
0,1001254,80014485718,40.64749,-73.97237,2020.0,10.0,9.0
1,1002102,52335172823,40.75362,-73.98377,2007.0,30.0,45.0
2,1002403,78829239556,40.80902,-73.94190,2005.0,3.0,0.0
3,1002755,85098326012,40.68514,-73.95976,2005.0,30.0,270.0
4,1003689,92037596077,40.79851,-73.94399,2009.0,10.0,9.0
...,...,...,...,...,...,...,...
102594,6092437,12312296767,40.70862,-73.94651,2003.0,1.0,0.0
102595,6092990,77864383453,40.80460,-73.96545,2016.0,1.0,1.0
102596,6093542,69050334417,40.67505,-73.98045,2009.0,3.0,0.0
102597,6094094,11160591270,40.74989,-73.93777,2015.0,2.0,5.0
102598,6094647,68170633372,40.76807,-73.98342,2010.0,1.0,0.0

In [ ]:
# id and host_id have to be a constant value but other column's value can be different
df.groupby('id')['host_id'].nunique()

id
1001254     1
1002102     1
1002403     1
1002755     1
1003689     1
           ..
57365208    1
57365760    1
57366313    1
57366865    1
57367417    1
Name: host_id, Length: 102050, dtype: int64

In [206]:
# function for checking outliers
# It will return True if outlier is present else it will return false
def check_outlier(column: str, df: pd.DataFrame) -> bool:
        
    Q1 = df[column].quantile(0.25)
    Q2 = df[column].median()
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_limit = Q1 - (IQR * 1.5)
    upper_limit = Q3 + (IQR * 1.5)

    return ((df[column] < lower_limit) | (df[column] > upper_limit)).any()

In [ ]:
for column in df.columns:
    if df[column].dtypes == "int64" or df[column].dtypes == "float64":
        if check_outlier(column=column, df=df):
            df[column] = df[column].replace(np.nan, df[column].median())
        else:
            df[column] = df[column].replace(np.nan, df[column].mean())